slater/__init__.py
from .app import create_app

__all__ = ['create_app']

slater/app.py
from . import extensions
from .views import views
from .api import api
from flask import Flask
import logging
import sys

def create_app(config_path='../slater.cfg'):
    app = Flask('slater')
    app.config.from_pyfile(config_path)
    configure_logging(app)
    extensions.init_app(app)
    app.register_blueprint(views)
    app.register_blueprint(api, url_prefix='/api')
    return app

def configure_logging(app):
    if app.debug:
        return

    app.logger.setLevel(logging.DEBUG)

    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    app.logger.addHandler(handler)

slater/auth.py
from functools import wraps
from flask import session, redirect, url_for, request

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        for attr in ['me', 'endpoint', 'access_token']:
           if (session.get("_micropub_{}".format(attr)) is None):
                return redirect(url_for('views.index', next=request.url))
        return f(*args, **kwargs)
    return decorated_function

def login_save_session(resp):
    session['_micropub_me'] = resp.me
    session['_micropub_endpoint'] = resp.micropub_endpoint
    session['_micropub_access_token'] = resp.access_token

slater/extensions/__init__.py
from flask_micropub import MicropubClient
from .micropub_config import MicropubConfig

micropub = MicropubClient()
micropub_config = MicropubConfig

def init_app(app):
    micropub.init_app(app, app.config["CLIENT_NAME"])

slater/views/__init__.py
from .views import views

__all__ = ['views']

slater/views/views.py
from flask import Blueprint, redirect, render_template, request, session, url_for

from ..extensions import micropub, micropub_config
from ..auth import login_required, login_save_session

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.jinja2')

@views.route('/authorize')
def authorize():
    return micropub.authorize(
        request.args.get('me'), next_url=url_for('.index'),
        scope=request.args.get('scope'))

@views.route('/micropub-callback')
@micropub.authorized_handler
def micropub_callback(resp):
    login_save_session(resp)
    mp_config = micropub_config(resp.micropub_endpoint, resp.access_token)
    session['_micropub_config'] = mp_config.mp_config
    return redirect(url_for('.new_event'))

@views.route('/new')
@login_required
def new_event():
    me = session.get('_micropub_me')
    endpoint = session.get('_micropub_endpoint')
    access_token = session.get('_micropub_access_token')
    mp_config = session.get('_micropub_config')
    return render_template(
      'new.jinja2', me=me,
      endpoint=endpoint,
      access_token=access_token,
      config=mp_config
    )

slater/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Slater</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skeleton.css') }}">

  <link rel="icon" href="{{ url_for('static', filename='images/slater-icon.png') }}" sizes="128x128" type="image/png">

  {% block head %}{% endblock %}
</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <header class="container">
    <h2><a href="{{ url_for('views.new_event') }}"><img class="logo" src="{{ url_for('static', filename='images/slater-icon.svg') }}"/></a> Slater - a <a href="https://www.w3.org/TR/micropub/">Micropub</a> client for events</h2>
  </header>
  {% block body %}{% endblock %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <footer class="container">
  <div>Slater is © 2017 by <a href="https://martymcgui.re/">Marty McGuire</a>. This code is <a href="https://github.com/martymcguire/slater">open source</a>. Feel free to send a pull request, or <a href="https://github.com/martymcguire/slater/issues">file an issue</a>.</div>
  <div>Calendar Icon by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">flaticon.com</a> is licensed <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
  </footer>
</body>
</html>

slater/templates/index.jinja2
{% extends "base.jinja2" %}

{% block body %}
<div class="container">
  <form action="{{ url_for('.authorize') }}" method="GET">
    <input type="hidden" name="scope" value="create media" />
    <div class="row">
      <div class="six columns">
        <label for="me">Sign In Using Your Website</label>
        <input class="util-full-width" type="text" name="me" placeholder="http://example.com" />
        <input class="button-primary" type="submit" value="Sign In" />
      </div>
    </div>
  </form>
</div>
{% endblock %}

slater/templates/new.jinja2
{% extends "base.jinja2" %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/flatpickr.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/tokenfield.css') }}">
  <style id="shame">
    [v-cloak] {
      display: none;
    }

    .photoPreview {
      box-shadow: rgba(0,0,0,0.2) 1px 1px 3px;
      display: inline-block;
      max-width: 33%;
      padding: 1rem;
      position: relative;
      width: 30%;
    }
    .photoPreview > img {
      width: 100%;
    }
    .photoPreview > button {
      background-color: rgba(255,0,0,0.3);
      border-radius: 50%;
      color: white;
      font-size: 2rem;
      height: 4rem;
      margin: 0;
      opacity: 0;
      padding: 0;
      position: absolute;
      right: -2rem;
      top: -2rem;
      width: 4rem;
    }
    .photoPreview > button:hover {
      background-color: rgba(255,0,0,1);
    }
    .photoPreview:hover > button {
      opacity: 1.0;
    }

    .tokenfield {
      box-sizing: border-box;
      margin-bottom: 15px;
      overflow: hidden;
    }
    .syndicate-to-option {
      background-color: rgba(0,0,0,0.15);
      border-radius: 0.5rem;
      display: inline-block;
      padding: 0.5rem 1rem;
    }
    .syndicate-to-option input {
      margin-bottom: 0;
    }
  </style>
  <script src="{{ url_for('static', filename='js/flatpickr.js') }}"></script>
  <script src="{{ url_for('static', filename='js/tokenfield.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/vue.js') }}"></script>
{% endblock %}
{% block body %}
<div class="container">
  <div class="two-thirds column">
    <form method="POST" action="{{ url_for('api.publish') }}" enctype="multipart/form-data">
      <input type="hidden" name="h" value="event" />
      <div class="row">
        <h4>Posting as <strong>{{ me }}</strong></h4>
      </div>
      <div class="row">
        <div class="util-full-width">
          <label for="name">Event Name</label>
          <input type="text" class="util-full-width" name="name" />
        </div>
      </div>
      <!-- TODO: date/time picker w/ TZ -->
      <div class="row">
        <div class="util-full-width">
          <label for="start">Start Date/Time</label>
          <input type="text" class="util-full-width datetime" name="start" placeholder="2016-12-06 19:30" />
        </div>
      </div>
      <!-- TODO: date/time picker w/ TZ -->
      <div class="row">
        <div class="util-full-width">
          <label for="end">End Date/Time</label>
          <input type="text" class="util-full-width datetime" name="end" placeholder="2016-12-06 21:30" />
        </div>
      </div>
      <!-- TODO: venue picker -->
      <div class="row">
        <div class="nine columns">
          <label for="location">Location</label>
          <input type="text" class="util-full-width" name="location" />
        </div>
        <div class="three columns">
          <label for="tzoffset">Timezone</label>
          <input type="text" class="util-full-width" name="tzoffset" placeholder="-05:00" />
        </div>
      </div>
      <div class="row">
        <div class="util-full-width">
          <label for="category">Categories</label>
          <input type="text" class="util-full-width" id="category" name="category" />
        </div>
      </div>
      <div class="row" id="photos">
        <div class="util-full-width">
          <label>Poster Image</label>
          {% raw %}
          <div v-if="photos.length > 0" v-cloak style="margin-bottom: 1.5rem">
            <div v-for="(photo,idx) of photos" class="photoPreview">
              <img :src="photo" />
              <button @click.prevent="removePhoto(idx)" title="Remove this photo">x</button>
              <input type="hidden" name="photo[]" :value="photo" />
            </div>
          </div>
          <div class="row" style="position: relative">
            <div class="add-file-inputs">
              <input type="text" class="util-full-width" name="photo[]" @change="addPhotoFromUrl" placeholder="Add Photo via URL" v-model="photoInput" />
              <div v-if="photoFile" v-cloak style="margin-bottom: 1.5rem">
                <div class="photoPreview">
                  <img :src="photoFile" />
                  <button @click.prevent="removePhotoFile" title="Remove this photo">x</button>
                </div>
              </div>
              <input class="util-full-width" type="file" name="photo" @change="addPhotoFromFile" ref="photoFileInput" title="Add Photo via Upload"/>
            </div>
          </div>
          {% endraw %}
        </div>
      </div>
      <div class="row">
        <div class="util-full-width">
          <label for="content">Description</label>
          <textarea class="util-full-width" name="content"></textarea>
        </div>
      </div>
      {% if config['syndicate-to'] %}
        <div class="row">
          <div class="util-full-width" style="margin-bottom: 2.5rem">
            <label>Syndicate-To</label>
            {% for synd in config['syndicate-to'] %}
            <label class="syndicate-to-option">
                <input type="checkbox" name="mp-syndicate-to[]" value="{{ synd.uid }}">
                <span class="label-body">{{ synd.name }}</span>
            </label>
            {% endfor %}
          </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="util-full-width">
          <input type="submit" class="button-primary" value="Create Event" />
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
  flatpickr("input.datetime", {
    enableTime: true,
    altInput: true,
    altFormat: "F j, Y h:i K"
  });

  var tf = new Tokenfield({
    el: document.getElementById("category"),
    newItems: true,
    newItemName: 'category'
  });
  var app = new Vue({
    el: '#photos',
    data: {
      'mp-config': {{ config | tojson | safe }},
      'photos': [],
      'photoFile': null,
      'photoInput': null
    },
    computed: {
      hasMediaEndpoint: function() {
        return(this['mp-config']['media-endpoint'] !== undefined)
      }
    },
    methods: {
      addPhotoFromUrl: function(){
        this.photos.push(this.photoInput);
        this.photoInput = null;
      },
      addPhotoFromFile: function(event){
        if (event && event.target.files[0]) {
          var file = event.target.files[0];
          this.photoFile = URL.createObjectURL(file);
          if(this.hasMediaEndpoint) {
            // Send file to micropub media endpoint
            var self = this;
            var formData = new FormData();
            formData.append('file', file);
            var request = new XMLHttpRequest();
            request.open("POST", "{{ url_for('api.publish_media') }}");
            request.onreadystatechange = function() {
              if(request.readyState == XMLHttpRequest.DONE) {
                try {
                  var response = JSON.parse(request.responseText);
                  if(response.location) {
                    self.photos.push(response.location);
                    self.removePhotoFile();
                  } else {
                    console.log("Endpoint did not return a location header", response);
                  }
                } catch(e) {
                  console.log(e);
                }
              }
            }
            request.send(formData);
          }
        } else {
          this.removePhotoFile();
        }
      },
      removePhoto: function(idx){
        this.photos.splice(idx,1);
      },
      removePhotoFile: function(){
        this.photoFile = null;
        this.$refs.photoFileInput.value = null;
      },
    }
  });
});
</script>
{% endblock %}

templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Slater</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="{{ url_for('static', filename='css/fonts.css') }}" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/skeleton.css') }}">

</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block body %}{% endblock %}

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

templates/index.jinja2
{% extends "base.jinja2" %}

{% block body %}
<div class="container">
  <form action="{{ url_for('authorize') }}" method="GET">
    <input type="hidden" name="scope" value="post" />
    <div class="row">
      <div class="six columns">
        <label for="me">Sign In Using Your Website</label>
        <input class="ut-full-width" type="text" name="me" placeholder="http://example.com" />
        <input class="button-primary" type="submit" value="Sign In" />
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/new.jinja2
{% extends "base.jinja2" %}

{% block body %}
<div class="container">
  <form method="POST" action="{{ endpoint }}" enctype="multipart/form-data">
    <input type="hidden" name="access_token" value="{{ access_token }}" />
    <input type="hidden" name="h" value="event" />
    <div class="row">
      <h4>Posting as <strong>{{ me }}</strong></h4>
    </div>
    <div class="row">
      <div class="two-thirds column">
        <label for="name">Event Name</label>
        <input type="text" class="ut-full-width" name="name" />
      </div>
    </div>
    <!-- TODO: date/time picker w/ TZ -->
    <div class="row">
      <div class="two-thirds column">
        <label for="start">Start Date/Time</label>
        <input type="text" class="ut-full-width" name="start" placeholder="2016-12-06 19:30 -05:00" />
      </div>
    </div>
    <!-- TODO: date/time picker w/ TZ -->
    <div class="row">
      <div class="two-thirds column">
        <label for="end">End Date/Time</label>
        <input type="text" class="ut-full-width" name="end" placeholder="2016-12-06 21:30 -05:00" />
      </div>
    </div>
    <!-- TODO: venue picker -->
    <div class="row">
      <div class="two-thirds column">
        <label for="location">Location</label>
        <input type="text" class="ut-full-width" name="location" />
      </div>
    </div>
    <!-- TODO: split on commas, strip whitespace, make into category[] on submit -->
    <div class="row">
      <div class="two-thirds column">
        <label for="category">Categories</label>
        <input type="text" class="ut-full-width" name="category" />
      </div>
    </div>
    <div class="row">
      <div class="two-thirds column">
        <label for="photo">Poster Image</label>
        <input type="file" name="photo" />
      </div>
    </div>
    <div class="row">
      <div class="two-thirds column">
        <label for="content">Description</label>
        <textarea class="ut-full-width" name="content"></textarea>
      </div>
    </div>
    <div class="row">
      <div class="two-thirds column">
        <input type="submit" class="button-primary" value="Create Event" />
      </div>
    </div>
  </form>
</div>
{% endblock %}